// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZgQhm7F7Khv7GPVKESOyW1oowSRgVkLg',
    appId: '1:486238586301:web:acf05f27d322c6a56a3ed4',
    messagingSenderId: '486238586301',
    projectId: 'pricematch-8c4cc',
    authDomain: 'pricematch-8c4cc.firebaseapp.com',
    storageBucket: 'pricematch-8c4cc.appspot.com',
    measurementId: 'G-3W9RWHNKBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjyQ5x8chR3NmvKRiZcPAEYpV1jq4o3k',
    appId: '1:486238586301:android:593bfd196836728d6a3ed4',
    messagingSenderId: '486238586301',
    projectId: 'pricematch-8c4cc',
    storageBucket: 'pricematch-8c4cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFX6BhKOmOGftQqTcfHZ1dRVX86NRGJv4',
    appId: '1:486238586301:ios:2081c2aa90bf6d646a3ed4',
    messagingSenderId: '486238586301',
    projectId: 'pricematch-8c4cc',
    storageBucket: 'pricematch-8c4cc.appspot.com',
    iosClientId: '486238586301-uo0qp80tk2vjduhk8pbippcrcnt92f1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricematchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFX6BhKOmOGftQqTcfHZ1dRVX86NRGJv4',
    appId: '1:486238586301:ios:2081c2aa90bf6d646a3ed4',
    messagingSenderId: '486238586301',
    projectId: 'pricematch-8c4cc',
    storageBucket: 'pricematch-8c4cc.appspot.com',
    iosClientId: '486238586301-uo0qp80tk2vjduhk8pbippcrcnt92f1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricematchapp',
  );
}
